package api.model

import javax.validation.constraints.NotNull

class FundTransferResponse {

    @NotNull
    internal var fundTransferStatus: FundTransferStatus? = null
    /**
     * a unique id to identify this transaction, this Id should be generated by the client
     */
    @NotNull
    internal var transactionRequestId: String? = null
}
