package model


import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull

class FundTransferRequest {
    /**
     * Auto increment database id
     */
    @NotNull
    @Min(value = 1, message = "Invalid id")
    var id: Int? = null

    /**
     * a unique id to identify this transaction, this Id should be generated by the client
     */
    @NotNull
    lateinit var transactionId: String

    /**
     * Identifier for the source account
     */
    @NotNull
    lateinit var sourceAccount: String

    /**
     * Identifier for the destination account
     */
    @NotNull
    lateinit var destinationAccount: String

    /**
     * The amount to be transferred in cents
     */
    @Min(value = 100, message = "You cannot transfer below 1 dollar ")
    @Max(value = 10000000, message = "You cannot transfer above 1000 dollars")
    var amountInCents: Int = 0
}
